# -*- coding: utf-8 -*-
"""making_transformers_efficient.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ar-w5gZwT0iCVJEfc3lMIoGmfKWHVioe

## **Loading the baseline model**
"""

from transformers import pipeline

bert_ckpt = "transformersbook/bert-base-uncased-finetuned-clinc"

pipe = pipeline("text-classification", model = bert_ckpt)

query = """
Hey, I'd like to rent a vehicle from Nov 1st to Nov 15th
in Paris and I need a 15 passenger van
"""

pipe(query)

"""## **Loading CLINC150**"""

from datasets import load_dataset

clinc = load_dataset("clinc/clinc_oos", "plus")

sample = clinc["test"][42]
sample

intents = clinc["test"].features["intent"]
intents.int2str(sample["intent"])

from evaluate import load
accuracy_score = load("accuracy")

"""## **The benchmark class**"""

class PerformanceBenchmark:
  def __init__(
      self,
      pipeline,
      dataset,
      optim_type = "BERT baseline"
  ):
    self.pipeline = pipeline
    self.datset = dataset
    self.optim_type = optim_type

  # computing accuracy
  def compute_accuracy(self):
    preds, labels = [], []

    for example in self.dataset:

      pred = self.pipeline(example["text"])[0]["label"]

      label = example["intent"]

      preds.append(intents.str2int(pred))

      labels.append(label)

    accuracy = accuracy_score.compute(
        predictions = preds,
        references = labels
    )

  def compute_size(self):
    pass

  def time_pipeline(self):
    pass

  def run_benchmark(self):
    metrics = {}
    metrics[self.optim_type] = self.compute_size()
    metrics[self.optim_type].update(self.time_pipeline())
    metrics[self.optim_type].update(self.compute_accuracy())

    return metrics